{% set name = "bqplot-gl" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bqplot-gl-{{ version }}.tar.gz
  sha256: 0173b9133d64e8c6929ca375a714e789b07286b1047b7509743c599495947795

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bqplot >=0.12,<0.13

test:
  imports:
    - bqplot_gl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bqplot/bqplot-gl
  summary: Plugin to bqplot powered by WebGL.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
